.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. betchip_qt test_betchip_qt
clean: FORCE
	$(MAKE) -C .. betchip_qt_clean test_betchip_qt_clean
check: FORCE
	$(MAKE) -C .. test_betchip_qt_check
betchip-qt betchip-qt.exe: FORCE
	 $(MAKE) -C .. betchip_qt
